# Generated by Django 5.0 on 2023-12-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Chat", "0002_chatserver_membership_chatserver_members_room_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True, default="avatars/default.webp", upload_to="media/avatars/"
            ),
        ),
    ]
