# Generated by Django 5.0 on 2023-12-15 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Chat", "0002_chatserver_membership_chatserver_members_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatserver",
            name="date_of_creation",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="chatserver",
            name="description",
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
