# Generated by Django 5.0 on 2023-12-15 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Chat", "0003_chatserver_date_of_creation_chatserver_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatserver",
            name="date_of_creation",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="chatserver",
            name="description",
            field=models.CharField(max_length=400),
        ),
    ]
