# Generated by Django 5.0 on 2023-12-22 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Chat", "0003_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together=set(),
        ),
    ]
