# Generated by Django 5.0 on 2023-12-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Chat", "0004_alter_chatserver_date_of_creation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Member"),
                    ("admin", "Admin"),
                    ("moderator", "Moderator"),
                ],
                default="member",
                max_length=10,
            ),
        ),
    ]
