# Generated by Django 5.0 on 2023-12-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Chat", "0005_alter_membership_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="server",
            new_name="chat_server",
        ),
        migrations.AddField(
            model_name="room",
            name="description",
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
