# Generated by Django 5.0 on 2023-12-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Chat", "0006_rename_server_room_chat_server_room_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.CharField(max_length=400),
        ),
    ]
