# Generated by Django 5.0 on 2023-12-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Chat", "0006_alter_message_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="nonce",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
